"""Primary sources cited across pages: (title, url, note)."""
S = {
    "sfop": ("IRS: U.S. Taxpayers Residing Outside the United States (Streamlined Foreign Offshore Procedures)",
             "https://www.irs.gov/individuals/international-taxpayers/us-taxpayers-residing-outside-the-united-states", ""),
    "sfcp": ("IRS: Streamlined Filing Compliance Procedures",
             "https://www.irs.gov/individuals/international-taxpayers/streamlined-filing-compliance-procedures", ""),
    "sfaq": ("IRS: Streamlined Filing Compliance Procedures FAQs", "https://www.irs.gov/node/13300", "(FAQs 2 and 3 cover Canadian retirement plans)"),
    "f14653": ("IRS Form 14653, Certification by U.S. Person Residing Outside of the U.S.", "https://www.irs.gov/pub/irs-pdf/f14653.pdf", ""),
    "fbarinst": ("FinCEN: BSA Electronic Filing Requirements for the FBAR (FinCEN Form 114)",
                 "https://www.fincen.gov/sites/default/files/shared/FBAR%20Line%20Item%20Filing%20Instructions.pdf", ""),
    "bsa": ("FinCEN BSA E-Filing System", "https://bsaefiling.fincen.treas.gov/", "(where the FBAR is filed)"),
    "fbarpen": ("31 CFR 1010.821, inflation-adjusted FBAR penalties", "https://www.law.cornell.edu/cfr/text/31/1010.821", ""),
    "bittner": ("Bittner v. United States, 598 U.S. 85 (2023)", "https://www.supremecourt.gov/opinions/22pdf/21-1195_4g15.pdf", ""),
    "i8938": ("IRS Instructions for Form 8938", "https://www.irs.gov/instructions/i8938", ""),
    "i3520": ("IRS Instructions for Form 3520", "https://www.irs.gov/instructions/i3520", ""),
    "i3520a": ("IRS Instructions for Form 3520-A", "https://www.irs.gov/instructions/i3520a", ""),
    "rp2017": ("Rev. Proc. 2020-17 (tax-favored foreign trusts)", "https://www.irs.gov/irb/2020-12_IRB#REV-PROC-2020-17", ""),
    "rp1455": ("Rev. Proc. 2014-55 (Canadian retirement plans)", "https://www.irs.gov/irb/2014-44_IRB", ""),
    "p597": ("IRS Publication 597, Information on the United States-Canada Income Tax Treaty", "https://www.irs.gov/publications/p597", ""),
    "i8621": ("IRS Instructions for Form 8621", "https://www.irs.gov/instructions/i8621", ""),
    "p915": ("IRS Publication 915, Social Security and Equivalent Railroad Retirement Benefits", "https://www.irs.gov/publications/p915", ""),
    "p514": ("IRS Publication 514, Foreign Tax Credit for Individuals", "https://www.irs.gov/publications/p514", ""),
    "i1116": ("IRS Instructions for Form 1116", "https://www.irs.gov/instructions/i1116", ""),
    "p54": ("IRS Publication 54, Tax Guide for U.S. Citizens and Resident Aliens Abroad", "https://www.irs.gov/publications/p54", ""),
    "i1040": ("IRS Instructions for Form 1040", "https://www.irs.gov/instructions/i1040gi", ""),
    "irsfx": ("IRS: Yearly average currency exchange rates", "https://www.irs.gov/individuals/international-taxpayers/yearly-average-currency-exchange-rates", ""),
    "treasfx": ("US Treasury: Treasury Reporting Rates of Exchange",
                "https://fiscaldata.treasury.gov/datasets/treasury-reporting-rates-exchange/treasury-reporting-rates-of-exchange", ""),
    "treaty": ("IRS: Canada tax treaty documents (convention, protocols, technical explanations)",
               "https://www.irs.gov/businesses/international-businesses/canada-tax-treaty-documents", ""),
    "reg6114": ("26 CFR 301.6114-1, treaty-based return positions (Form 8833)", "https://www.law.cornell.edu/cfr/text/26/301.6114-1", ""),
}
